// Canonical package definitions (read-only)
export const PACKAGES = [
  // Visual production — time-based packages from src/pages/VisualProduction.tsx
  {
    productCode: "VIS-2H",
    serviceId: "birthday_photography",
    displayName: "2-Hour Coverage",
    packageTier: "basic",
    coverageType: null,
    features: ["Key moments", "Edited highlights", "Digital delivery"],
    frontendLabels: ["2-Hour Coverage", "General Shoot"],
  },
  {
    productCode: "VIS-4H",
    serviceId: "birthday_photography",
    displayName: "4-Hour Coverage",
    packageTier: "standard",
    coverageType: null,
    features: ["Comprehensive coverage", "Multiple angles", "Color grading"],
    frontendLabels: ["4-Hour Coverage"],
  },
  {
    productCode: "VIS-6H",
    serviceId: "birthday_photography",
    displayName: "6-Hour Coverage",
    packageTier: "premium",
    coverageType: null,
    features: ["Extended coverage", "Priority editing"],
    frontendLabels: ["6-Hour Coverage"],
  },
  // Web development offerings (examples from frontend pages)
  {
    productCode: "WEB-LP",
    serviceId: "web_development",
    displayName: "Landing Page",
    packageTier: "basic",
    coverageType: null,
    features: ["Single-page site", "Basic content"],
    frontendLabels: ["Landing Page"],
  },
  {
    productCode: "WEB-BIZ",
    serviceId: "web_development",
    displayName: "Business Website",
    packageTier: "standard",
    coverageType: null,
    features: ["Multi-page", "CMS"],
    frontendLabels: ["Business Website"],
  },
  {
    productCode: "WEB-CUST",
    serviceId: "web_development",
    displayName: "Custom Web App",
    packageTier: "premium",
    coverageType: null,
    features: ["Custom features", "API integrations"],
    frontendLabels: ["Custom / Web App", "Website Project"],
  },
  // Audio example
  {
    productCode: "AUD-GEN",
    serviceId: "audio_production",
    displayName: "General Session",
    packageTier: "basic",
    coverageType: null,
    features: ["Studio recording"],
    frontendLabels: ["General Session"],
  },
  // Inquiry / intake types (metadata-only, non-billable)
  {
    productCode: "INQ-GEN",
    serviceId: null,
    displayName: "General Inquiry",
    entityType: "inquiry",
    workflowType: "intake_general",
    billable: false,
    requiresManualScoping: true,
    frontendLabels: ["General Inquiry", "Digital Inquiry", "General Project"],
  },
  {
    productCode: "INQ-STRAT",
    serviceId: null,
    displayName: "Strategy / Consultation",
    entityType: "inquiry",
    workflowType: "intake_strategy",
    billable: false,
    requiresManualScoping: true,
    frontendLabels: ["Strategy Session", "Strategic Consultation", "Strategy Session"],
  },
  {
    productCode: "INQ-KICKOFF",
    serviceId: null,
    displayName: "Project Kickoff / Initial Consultation",
    entityType: "inquiry",
    workflowType: "intake_kickoff",
    billable: false,
    requiresManualScoping: true,
    frontendLabels: ["Project Kickoff", "Initial Consultation"],
  },
  {
    productCode: "INQ-AUDIT",
    serviceId: null,
    displayName: "Audit / Assessment",
    entityType: "inquiry",
    workflowType: "intake_audit",
    billable: false,
    requiresManualScoping: true,
    frontendLabels: ["Data Audit", "General Audit"],
  },
  {
    productCode: "INQ-PROD",
    serviceId: null,
    displayName: "Production Inquiry",
    entityType: "inquiry",
    workflowType: "intake_production",
    billable: false,
    requiresManualScoping: true,
    frontendLabels: ["Production Inquiry"],
  },
  {
    productCode: "INQ-MGMT",
    serviceId: null,
    displayName: "Management / Project Management Inquiry",
    entityType: "inquiry",
    workflowType: "intake_management",
    billable: false,
    requiresManualScoping: true,
    frontendLabels: ["Management Inquiry", "Management Project"],
  },
];

export default PACKAGES;
